### ISSUE TITLE
keepchen,希仁之拥的博客

### ISSUE THREAD

**Issue by keepchen** [keepchen/blog-comments#55]
https://blog.keepchen.com/about 

 【blog.keepchen.com】是keepchen(希仁之拥，陈金平，金平)的个人博客站，正所谓:好记性不如烂笔头，站内不定时会发布原创文章以及转载分享一些(自认为)有质量的文章，文章内容包括但不限于IT技术、生活分享、歌曲分享、随笔记录、拍照美图等，算是个人资源收集站。© blog.keepchen.com

**Comment by keepchen** [comment]
#### 友链申请要求  
---  
- ✅ 网站能够正常访问  
- ✅ 网站类型为个人博客  
- ✅ 网站需要包含本站友链(dofollow，相互的)  
- ✅ 网站需要开通一年以上，且原创文章不少于20篇  
- ✅ 可接受良性的商业性站点(不能包含NSFW内容)  
- ✅ 可接受开源项目仓库/站点/文档站  
- ❌ 不接受违反中华人民共和国法律法规的站点  

如果符合上述条件，可在本页面评论区留言您的站点信息，格式如下：  
```yaml  
name: 希仁之拥 # 站点名称
desc: 独立开发者 & 开源爱好者。喜欢猫猫狗狗、花花草草，热衷于创造酷酷的东西。 —— 希仁之拥 © blog.keepchen.com # 站点介绍  
logo: https://blog.keepchen.com/favicon.ico # 站点图标地址
link: https://blog.keepchen.com # 访问链接  
```  

**申请前记得先添加本站噢～**
