### ISSUE TITLE
链接 | 希仁之拥的博客

### ISSUE THREAD

**Issue by keepchen** [keepchen/blog-comments#75]
https://blog.keepchen.com/links 

 这里展示了希仁之拥收录的链接，包含各种的博客、酷站、产品等等。如果你也想让你的站点展示在这里，欢迎在页面下方留言。

**Comment by keepchen** [comment]
#### 友链申请要求  
---  
- ✅ 网站能够正常访问  
- ✅ 网站类型为个人博客  
- ✅ 网站需要包含本站友链(dofollow，相互的)  
- ✅ 网站需要开通一年以上，且原创文章不少于20篇  
- ✅ 可接受良性的商业性站点(不能包含NSFW内容)  
- ✅ 可接受开源项目仓库/站点/文档站  
- ❌ 不接受违反中华人民共和国法律法规的站点  

如果符合上述条件，可在本页面评论区留言您的站点信息，格式如下：  
```yaml  
name: 希仁之拥 # 站点名称
desc: 独立开发者 & 开源爱好者。喜欢猫猫狗狗、花花草草，热衷于创造酷酷的东西。 —— 希仁之拥 © blog.keepchen.com # 站点介绍  
logo: https://blog.keepchen.com/favicon.ico # 站点图标地址
link: https://blog.keepchen.com # 访问链接  
```  

**申请前记得先添加本站噢～**
